### ISSUE TITLE
Update the license to BSD

### ISSUE THREAD

**Issue by mostaphaRoudsari** [pollination/api#14]
We [most likely] need to change the license to comply with IN2 project.

I'm still not sure if this is required. The fork can be changed from MIT to BSD and then the changes coming back for IN2 can be merged back under the license of this repository ( MIT). The main challenge will be adding/ removing contribution credits which MIT allows but BSD does not. Going BSD on both sides probably makes this all easier.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I don't think MIT allows the removal of contribution credit since the license says that the [copyright notice is supposed to be included in all copies of the software](https://github.com/pollination/api/blob/master/LICENSE#L12-L13). Put another way, the only way that such a copyright might be removed is by arguing that new code is not a copy of the original but a derivative work of it or by arguing that whatever is copied is not a substantial portion of the software.  These could describe some of the work on the energy modeling extension of the schema since it is a relatively small fraction of the whole repo and it cannot be run on its own without the other code from the repo.

My understanding about the difference between BSD and MIT is that they are functionally the same except that BSD 3-clause adds a restriction about how the software can be advertised (in the third clause):

> (3) Neither the name of the copyright holder nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission from the respective party.

I guess the important question for us is whether we feel strongly about anyone to be able to use pollination to advertise their product without our consent?  Such advertisement could be a good thing for us so maybe it might be better to argue that the work on the energy model schema is a derivative work.  This will make it difficult for us to have synced forks, though.  So, if we don't feel strongly about this advertisement, it is better to just switch the licence over to BSD 3-caluse.

And one glaring thing that I noticed:
Who is Ivan Goncharov and [why does he hold the copyright of Pollination API](https://github.com/pollination/api/blob/master/LICENSE#L3)?

**Comment by chriswmackey** [comment]
You are right that BSD seems a bit more hard lined in that it does not include a note about "substantial portions" of the software when defining what counts as a copy of the software.

However, I think someone could still make the argument that certain code need not carry the original copyright if it is a derivative work and not a copy/redistribution of a BSD project.  As a derivative work, it would still need to respect the third clause, though:

> (3) Neither the name of the copyright holder nor the names of any contributors may be used to endorse or promote products derived from this software without specific prior written permission from the respective party.

I guess the important question for us is whether we feel strongly about anyone to be able to use pollination API to advertise their product without our consent?  If we don't feel strongly about people being able to use pollination API in their advertisements, it seems better to just switch the pollination licence over to BSD 3-clause.

If we do feel strongly about this, then we may have to get into the complexity of arguing that pollination API is a derivative work of a wholly separate repo where the energy-model-schema work is going on.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey we can finally get this started. Let's talk about it later today and get it over to energy-schema repository.
